"""initial

Revision ID: 2bd242185be4
Revises: 
Create Date: 2023-12-03 12:20:46.872444

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bd242185be4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('psw', sa.String(length=500), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('demand',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('medicine_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('surname', sa.String(length=50), nullable=False),
                    sa.Column('address', sa.String(length=500), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('purchase',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('purchase_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('purchase_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('purchase_id', sa.Integer(), nullable=True),
                    sa.Column('medicine_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
                    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_item')
    op.drop_table('purchase')
    op.drop_table('profile')
    op.drop_table('demand')
    op.drop_table('user')
    op.drop_table('medicine')
    # ### end Alembic commands ###
