"""change purchase model

Revision ID: 90442886d645
Revises: e041027a58d1
Create Date: 2023-12-04 01:23:20.654105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90442886d645'
down_revision: Union[str, None] = 'e041027a58d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_item')
    op.add_column('purchase', sa.Column('medicine_id', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase', 'medicine', ['medicine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'quantity')
    op.drop_column('purchase', 'medicine_id')
    op.create_table('purchase_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), nullable=True),
    sa.Column('medicine_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
