"""add col demand to medicine

Revision ID: e041027a58d1
Revises: 891dfe950ca0
Create Date: 2023-12-03 23:57:11.425006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e041027a58d1'
down_revision: Union[str, None] = '891dfe950ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    op.add_column('medicine', sa.Column('demand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'demand')
    op.create_table('demand',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
